import type { SearchChunk } from "@/lib/search/chunks";

/** Embedding model shared by the build-time indexer and the in-browser query. */
export const SEARCH_MODEL_ID = "Xenova/all-MiniLM-L6-v2";

export const EMBEDDING_DIMS = 384;

/** Quantization level — must match between index build and browser query. */
export const EMBEDDING_DTYPE = "q8";

/** Generated by scripts/build-search-index.ts, served from public/. */
export const SEARCH_INDEX_PATH = "/search-index.json";

/** 2D PCA projection of the index, for the Lab's embedding map. */
export const SEARCH_MAP_PATH = "/search-map.json";

/** Dispatched on window to open the palette from anywhere (e.g. the nav button). */
export const OPEN_SEARCH_EVENT = "rs-open-search";

export interface IndexedChunk extends SearchChunk {
  /** Mean-pooled, normalized embedding rounded to 4 decimal places. */
  vec: ReadonlyArray<number>;
}

export interface SearchIndex {
  model: string;
  dims: number;
  contentHash: string;
  chunks: ReadonlyArray<IndexedChunk>;
}

export interface SearchMapPoint {
  id: string;
  label: string;
  /** Normalized 0..1 within the map's PCA range. */
  x: number;
  y: number;
  route: string;
  anchor: string;
}

export interface SearchMap {
  contentHash: string;
  /** Column mean of the chunk vectors — subtract before projecting. */
  mean: ReadonlyArray<number>;
  /** Top-2 principal components (unit vectors). */
  components: ReadonlyArray<ReadonlyArray<number>>;
  /** Raw projection ranges used for the 0..1 normalization. */
  range: { x: [number, number]; y: [number, number] };
  points: ReadonlyArray<SearchMapPoint>;
}
