import type { SearchChunk } from "@/lib/search/chunks";

/** Embedding model shared by the build-time indexer and the in-browser query. */
export const SEARCH_MODEL_ID = "Xenova/all-MiniLM-L6-v2";

export const EMBEDDING_DIMS = 384;

/** Quantization level — must match between index build and browser query. */
export const EMBEDDING_DTYPE = "q8";

/** Generated by scripts/build-search-index.ts, served from public/. */
export const SEARCH_INDEX_PATH = "/search-index.json";

/** Dispatched on window to open the palette from anywhere (e.g. the nav button). */
export const OPEN_SEARCH_EVENT = "rs-open-search";

export interface IndexedChunk extends SearchChunk {
  /** Mean-pooled, normalized embedding rounded to 4 decimal places. */
  vec: ReadonlyArray<number>;
}

export interface SearchIndex {
  model: string;
  dims: number;
  contentHash: string;
  chunks: ReadonlyArray<IndexedChunk>;
}
